name: Monitor Kubernetes Costs
on:
  schedule:
    - cron: '0 0 * * *'  # Daily at midnight UTC (1 AM CEST)
  workflow_dispatch:  # Enables manual triggering
jobs:
  check-metrics:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Ensure script permissions
      run: chmod +x scripts/check-metrics.sh
    - name: Install deps
      run: sudo apt-get update && sudo apt-get install -y curl jq bc
    - name: Run metric check
      id: check-metrics
      env:
        COCKPIT_TOKEN: ${{ secrets.COCKPIT_TOKEN }}
        DATA_SOURCE_ID: d2967af6-7cae-4d15-bcf6-d128c3c2f81b
        CLUSTER_NAME: k8s-triggeriq-fe-cluster
      run: |
        OUTPUT=$(./scripts/check-metrics.sh "$COCKPIT_TOKEN" "$DATA_SOURCE_ID" "$CLUSTER_NAME")
        echo "$OUTPUT"
        
        # Extract metrics from the script output
        CPU=$(echo "$OUTPUT" | grep -E "Cluster CPU usage:|ALERT: Cluster CPU" | grep -o '[0-9.]*%' | head -1 | tr -d '%' || echo "unknown")
        MEMORY=$(echo "$OUTPUT" | grep "Memory usage:" | grep -o '[0-9.]*%' | tr -d '%' || echo "unknown")
        NODE_COUNT=$(echo "$OUTPUT" | grep "Cluster node count:" | grep -o '[0-9]*' || echo "unknown")
        CONTROLPLANE=$(echo "$OUTPUT" | grep "Control plane:" | awk '{print $NF}' || echo "unknown")
        INSTANCE_CPU=$(echo "$OUTPUT" | grep "Instance CPU" | grep -o '[0-9.]*%' | tr -d '%' || echo "unknown")
        
        # Determine CPU status
        if [ "$CPU" != "unknown" ] && [ $(echo "$CPU < 20" | bc -l) -eq 1 ]; then
          CPU_STATUS="🚨 LOW - consider downsizing!"
        else
          CPU_STATUS="✅ Healthy"
        fi
        
        # Debug extracted values
        echo "Extracted values:"
        echo "CPU: $CPU"
        echo "Memory: $MEMORY"
        echo "Node Count: $NODE_COUNT"
        echo "Control Plane: $CONTROLPLANE"
        echo "Instance CPU: $INSTANCE_CPU"
        echo "CPU Status: $CPU_STATUS"
        
        # Set outputs
        echo "cpu=$CPU" >> $GITHUB_OUTPUT
        echo "memory=$MEMORY" >> $GITHUB_OUTPUT
        echo "node_count=$NODE_COUNT" >> $GITHUB_OUTPUT
        echo "controlplane=$CONTROLPLANE" >> $GITHUB_OUTPUT
        echo "instance_cpu=$INSTANCE_CPU" >> $GITHUB_OUTPUT
        echo "cpu_status=$CPU_STATUS" >> $GITHUB_OUTPUT
    - name: Notify Slack
      uses: slackapi/slack-github-action@v2.1.1
      with:
        method: chat.postMessage
        token: ${{ secrets.SLACK_BOT_TOKEN }}
        payload: |
          {
            "channel": "D09GZCRDRNE",
            "text": "📊 Daily Cost Check for k8s-triggeriq-fe-cluster:\n• Cluster CPU: ${{ steps.check-metrics.outputs.cpu }}% - ${{ steps.check-metrics.outputs.cpu_status }}\n• Memory Usage: ${{ steps.check-metrics.outputs.memory }}%\n• Node Count: ${{ steps.check-metrics.outputs.node_count }}\n• Control Plane: ${{ steps.check-metrics.outputs.controlplane }}\n• Instance CPU (avg): ${{ steps.check-metrics.outputs.instance_cpu }}%"
          }
