name: Monitor Kubernetes Costs
on:
  schedule:
    - cron: '0 0 * * *'  # Daily at midnight UTC (1 AM CEST)
  workflow_dispatch:  # Enables manual triggering
jobs:
  check-metrics:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Ensure script permissions
      run: chmod +x scripts/check-metrics.sh
    - name: Install deps
      run: sudo apt-get update && sudo apt-get install -y curl jq
    - name: Run metric check
      id: check-metrics
      env:
        API_KEY: ${{ secrets.SCALEWAY_API_KEY }}
        PROJECT_ID: ${{ secrets.SCALEWAY_PROJECT_ID }}
        CLUSTER_NAME: k8s-triggeriq-fe-cluster
      run: |
        OUTPUT=$(./scripts/check-metrics.sh $API_KEY $PROJECT_ID $CLUSTER_NAME)
        echo "$OUTPUT"
        echo "cpu=$(echo "$OUTPUT" | grep -E "Cluster CPU usage|ERROR.*cluster CPU" | tail -1 | awk '{print $NF}' | tr -d '%')" >> $GITHUB_OUTPUT
        echo "triggeriq_cpu=$(echo "$OUTPUT" | grep -E "triggeriq CPU|ERROR.*triggeriq CPU" | tail -1 | awk '{print $3}')" >> $GITHUB_OUTPUT
        echo "watchers=$(echo "$OUTPUT" | grep -E "ingress-nginx etcd watchers|ERROR.*etcd watchers" | tail -1 | awk '{print $4}')" >> $GITHUB_OUTPUT
        echo "http_rate=$(echo "$OUTPUT" | grep -E "triggeriq HTTP rate|ERROR.*HTTP rate" | tail -1 | awk '{print $4}')" >> $GITHUB_OUTPUT
    - name: Notify Slack
      uses: slackapi/slack-github-action@v1.24
      with:
        slack-bot-token: ${{ secrets.SLACK_TOKEN }}
        channel-id: D09GZCRDRNE
        text: |
          Daily Cost Check for $CLUSTER_NAME:
          Cluster CPU: ${{ steps.check-metrics.outputs.cpu }}
          triggeriq CPU: ${{ steps.check-metrics.outputs.triggeriq_cpu }}
          ingress-nginx Watchers: ${{ steps.check-metrics.outputs.watchers }}
          triggeriq HTTP Rate: ${{ steps.check-metrics.outputs.http_rate }}
